# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import locus_message_pb2 as locus__message__pb2


class LocusMessagerStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.SendLocus = channel.unary_unary(
                '/locus_package.LocusMessager/SendLocus',
                request_serializer=locus__message__pb2.Locus.SerializeToString,
                response_deserializer=locus__message__pb2.FilterExecution.FromString,
                )


class LocusMessagerServicer(object):
    """Missing associated documentation comment in .proto file."""

    def SendLocus(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_LocusMessagerServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'SendLocus': grpc.unary_unary_rpc_method_handler(
                    servicer.SendLocus,
                    request_deserializer=locus__message__pb2.Locus.FromString,
                    response_serializer=locus__message__pb2.FilterExecution.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'locus_package.LocusMessager', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class LocusMessager(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def SendLocus(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/locus_package.LocusMessager/SendLocus',
            locus__message__pb2.Locus.SerializeToString,
            locus__message__pb2.FilterExecution.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
